# Generated by Django 3.2.16 on 2023-01-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Service name', max_length=100, null=True)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Service price', null=True)),
                ('details', models.JSONField(blank=True, help_text='Service details', null=True)),
                ('view_order', models.PositiveIntegerField(blank=True, help_text='Order of this service', null=True)),
                ('status', models.BooleanField(default=True, help_text='Is service is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Package creation time')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Package name', max_length=100, null=True)),
                ('price', models.PositiveIntegerField(blank=True, help_text='Package price', null=True)),
                ('details', models.JSONField(blank=True, help_text='Package details', null=True)),
                ('status', models.BooleanField(default=True, help_text='Is package is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Package creation time')),
                ('service', models.ManyToManyField(to='packages.ServiceModel')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
    ]
