# Generated by Django 3.2.16 on 2023-01-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='service',
            field=models.ManyToManyField(related_name='package_service', to='packages.ServiceModel'),
        ),
    ]
